name: Broken Link Checker

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sundays
  pull_request:
    paths:
      - "**/*.md"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Links
        uses: lycheeverse/lychee-action@v2
        with:
          # Scan all markdown files in the repo for broken external links
          args: --verbose --no-progress './**/*.md'
          fail: true
